language: elixir
elixir:
  - 1.10
otp_release:
  - 21.0
env:
  matrix:
    - DECIMAL_VERSION=1
    - DECIMAL_VERSION=2
script:
  - bin/test
after_script:
  - MIX_ENV=dev mix deps.get
  - MIX_ENV=dev mix inch.report
